apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    name: letsencrypt-staging
spec:
  acme:
    email: your@email.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          groupName: dns.services.cert-manager.io
          solverName: dns.services.cert-manager.io
          config:
              usernameSecretRef: 
                name: dns-services
                key: username
              passwordSecretRef: 
                name: dns-services
                key: password
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    name: letsencrypt
spec:
  acme:
    email: your@email.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          groupName: dns.services.cert-manager.io
          solverName: dns.services.cert-manager.io
          config:
              usernameSecretRef: 
                name: dns-services
                key: username
              passwordSecretRef: 
                name: dns-services
                key: password
